modLoader="kotlinforforge" #mandatory
loaderVersion="[4.3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Apache 2.0 with Commons Clause"
issueTrackerURL="https://github.com/davo899/CobblemonMegas/issues"

[[mods]] #mandatory
modId="cobblemonmegas" #mandatory
version="${version}" #mandatory
displayName="CobblemonMegas" #mandatory
displayURL="https://github.com/davo899/CobblemonMegas"
#logoFile="examplemod.png" #optional
authors="selfdot"
description=""

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.cobblemonmegas]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"

[[dependencies.cobblemonmegas]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47,)" #mandatory

[[dependencies.cobblemonmegas]]
modId="architectury"
mandatory=true
versionRange="[9.1.12,)"